### PR TITLE
translate to GE - Tyres

### PR DESCRIPTION
**Pull request by PeBueGo**

### CODE REVIEW

**Comment by fesch** [comment]
@yoh-there Is this merge for you OK too?

**Comment by yoh-there** [comment]
My comments, please assess them:

@PeBueGo DC power is not "ladestation". It's what really is on the battery


@PeBueGo SOH is health, not lebensdauer (I think that was in the old translation too)


@PeBueGo @fesch Personally I loathe "motor on/off", it's so silly but I rest my case as renault calls it that way, and in general, if we give responsability to a maintainer because we can't do it ourselves, we should be humble :-)

@PeBueGo @fesch I am nervous about the modifications outside the /de/ folder

@fesch I think you merged the previous translation into master; if not nil this comment. I would suggest to only modify master at release instances so we can much more easily investigate crashes and ANRs.

**Comment by fesch** [comment]
@yoh-there : You are right I merged the previous one into master, as this was the request. I didn't pay attention :-/ ...

**Comment by fesch** [comment]
@yoh-there : Modifications outside the DE folder seam fine for me.

**Comment by fesch** [comment]
@PeBueGo : I close this now. Please make a new pull-request into the "Developpment" branches. 

- Thanks -

**Comment by PeBueGo** [comment]
> My comments, please assess them:
> 
> @PeBueGo DC power is not "ladestation". It's what really is on the battery
> 
> @PeBueGo SOH is health, not lebensdauer (I think that was in the old translation too)
> 
> @PeBueGo @fesch Personally I loathe "motor on/off", it's so silly but I rest my case as renault calls it that way, and in general, if we give responsability to a maintainer because we can't do it ourselves, we should be humble :-)
> 
> @PeBueGo @fesch I am nervous about the modifications outside the /de/ folder
> 
> @fesch I think you merged the previous translation into master; if not nil this comment. I would suggest to only modify master at release instances so we can much more easily investigate crashes and ANRs.


> @PeBueGo : I close this now. Please make a new pull-request into the "Developpment" branches.
> 
>     * Thanks -

Thanks for reply
changes will be done in next merge

**Pull request closed without merging**
