### PR TITLE
Ukrainian/Russian translations

### PR DESCRIPTION
**Pull request by landswellsong**
Hello
Here in Ukraine we're having a very spectacular EV growth and especially that of Zoes in recent years, so your app is quite popular. I've added Ukrainian and Russian strings. 

Couple of things to note:
- Some strings aren't in the translations, most importantly various values (e.g. state of charge names, HVAC loop name etc etc), didn't do anything about it
image

- I had to uncheck the `untranslatable` flag from the unit names, because we use Cyrillics and some of units are very differently spelled here as well. I've copied the English version over all of the other languages so it isn't marked as incomplete for those languages.
- Fixed 2 apparent typos in English which I stumbled upon (separate commit)

### CODE REVIEW

**Comment by fesch** [comment]
Could you please mage a pull request into the development branch?

**Comment by fesch** [comment]
Could you please mage a pull request into the development branch?

**Comment by landswellsong** [comment]
@fesch oops, will do

**Comment by landswellsong** [comment]
Rebased my branch and force-pushed, should be fine now.

**Comment by fesch** [comment]
thanks ;)

**Pull request merged**
