### PR TITLE
Added reference check, displays < ref if firmware is older than expected, > ref if firmware is new than expected.

### PR DESCRIPTION
**Pull request by yoh-there**
Added reference check, displays < ref if firmware is older than expected, > ref if firmware is new than expected.

### CODE REVIEW

**Comment by fesch** [comment]
This is what I get displayed:
screenshot_2015-10-03-12-44-05

**Comment by yoh-there** [comment]
Thank you!! I think a trip to the garage is needed Bob ;-)

I am happy elm still works for you. I am very curious of your findings,
functional and stability wise.

Op za 3 okt. 2015 12:47 schreef Bob Fisch notifications@github.com:

> This is what I get displayed:
> [image: screenshot_2015-10-03-12-44-05]
> https://cloud.githubusercontent.com/assets/1027354/10262542/e2a7b55c-69cc-11e5-8aac-820a63499825.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fesch/CanZE/pull/59#issuecomment-145236361.
> 
> ## 
- Sent from my phone, so please pardon any terseness or typos -

**Comment by fesch** [comment]
Indeed ;-)

**Comment by StephanHi** [comment]
Are reference firmware versions no longer displayed in V1.21 build 2017.01.29@20:10?

**Comment by yoh-there** [comment]
That is correct. By now there are too many versions of cars out with too many software (sub) versions. There is simply not enough feedback to keep this going.

**Comment by StephanHi** [comment]
Understandable. But you should update the user guide on http://canze.fisch.lu/user-guide/ (section Firmware -> Information) accordingly.
Thanks!

**Pull request merged**
