### PR TITLE
Changed car to bit-map in fields. Changed immediate consumption graph to a Low pass filtered value in a much more limited range. A bit experimental. Added 12V in charging, which is not functioning well for the Zoe, needs more debugging

### PR DESCRIPTION
**Pull request by yoh-there**
Changed car to bit-map in fields. Changed immediate consumption graph to a Low pass filtered value in a much more limited range. A bit experimental. Added 12V in charging, which is not functioning well for the Zoe, needs more debugging

### CODE REVIEW

**Comment by fesch** [comment]
In the consumption screen the upper bars must be labeled again. The way it is now, there is no indication about what they represent ...

**Comment by yoh-there** [comment]
Maybe ;-) I am still experimenting, but things got too diverted in the
source code. Problem is that I feel is that the value is needed, especially
on the consumption, but adding the label makes it even more unreadable with
the deeply colored bar under the text. Maybe a non-transparent background
box under the text?

On Sun, Jan 24, 2016 at 9:57 PM, Bob Fisch notifications@github.com wrote:

> In the consumption screen the upper bars must be labeled again. The way it
> is now, there is no indication about what they represent ...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fesch/CanZE/pull/306#issuecomment-174341087.

## 

Please use Signal to reach me on secure IM and VoIP http://sgnl.link/1KpeYmF

**Comment by fesch** [comment]
I've now tried a left / right positioning. On my 7'' tablet it looks quite well, but I don't have tested on a smaller device right now-.

**Comment by yoh-there** [comment]
Lets try it like this :-)

Need to experiment with the LPF in the second graph anyway (it seems to wrk
fine, give it a spin please). And the 12V system.

On Sun, Jan 24, 2016 at 10:05 PM, Bob Fisch notifications@github.com
wrote:

> I've now tried a left / right positioning. On my 7'' tablet it looks quite
> well, but I don't have tested on a smaller device right now-.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fesch/CanZE/pull/306#issuecomment-174341591.

## 

Please use Signal to reach me on secure IM and VoIP http://sgnl.link/1KpeYmF

**Comment by fesch** [comment]
the new graph scale is better for values in the given range, but actually it now misses it's first need: display the instant average consumption over time. In fact, most of my values are outside the range, so I just see some lines going up and down.

The value in the upper bar does a good job. I think we need to enlarge it, because for me it's somewhat too small right now.

**Comment by yoh-there** [comment]
Hi Bob,

In the last commit I changed the coloring of the bars a bit to make the
(black) numbers more readable. I think it is fine.

I will now proceed with further optimizing the fields. I only want to
create objects for the fields we use and I already made a column in the
spreadsheet "used by CanZE" for that. Now, there are two approaches to this

1) The options bit mapped field determines for which cars the field is
initialized. We now default it to 0x1f, meaning all cars, unless we need
differentiation. If we default the to 0x00 if the "used in CanZE", the code
that processes the long string will simply skip over the unused fields.

2) We can simply put two // in from of each line that is not used by CanZE.
This way, if we by incident forget to set a "used by CanZE", we can simply
remove the // and everything is fixed (instead of fiddling with the hex
code). It requires no code change, just spreadsheet change.

Personally I have a rather strong preference for option 2. It will make
everything (initialization and memory use) smaller and faster, more than
option 1, and it is easier to maintain.

What do you think?

Jeroen

On Mon, Jan 25, 2016 at 9:39 AM, Jeroen Meijer meijer.jwm@gmail.com wrote:

> On the second, I agree.
> 
> On the first. I am not sure I agree, let me show you my highway trip to
> Amsterdam this AM, including a small holdup. The (very simple) Low Pass
> filter works fine I think
> 
> https://drive.google.com/file/d/1kbk6YemzH9tzOIKysTOq_O36RUw4zAk9WQ/view?usp=sharing
> 
> New bug: Torque value doesn't display. I will fix that.
> 
> On Mon, Jan 25, 2016 at 8:56 AM, Bob Fisch notifications@github.com
> wrote:
> 
> > the new graph scale is better for values in the given range, but actually
> > it now misses it's first need: display the instant average consumption over
> > time. In fact, most of my values are outside the range, so I just see some
> > lines going up and down.
> > 
> > The value in the upper bar does a good job. I think we need to enlarge
> > it, because for me it's somewhat too small right now.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/fesch/CanZE/pull/306#issuecomment-174430864.
> 
> ## 
> 
> Please use Signal to reach me on secure IM and VoIP
> http://sgnl.link/1KpeYmF

## 

Please use Signal to reach me on secure IM and VoIP http://sgnl.link/1KpeYmF

**Comment by fesch** [comment]
Hi

Actually my tablet's battery is empty, so I am unable to test until
recharged :-(

But yes, if you intend to reduce the code size and thus the memory
finger print, I think that option #2 is the best, as it really removes
everything that is not needed.

greetings
Bob

**Comment by yoh-there** [comment]
I made the spreadsheet changes, copied it to Fields and put it on my phone.
Will check on my way home. If all is OK, I'll commit it tonight.

On Wed, Jan 27, 2016 at 8:31 AM, Bob Fisch notifications@github.com wrote:

> Hi
> 
> Actually my tablet's battery is empty, so I am unable to test until
> recharged :-(
> 
> But yes, if you intend to reduce the code size and thus the memory
> finger print, I think that option #2 is the best, as it really removes
> everything that is not needed.
> 
> greetings
> Bob
> 
> On 27.01.2016 0:04 , yoh-there wrote:
> 
> > Hi Bob,
> > 
> > In the last commit I changed the coloring of the bars a bit to make the
> > (black) numbers more readable. I think it is fine.
> > 
> > I will now proceed with further optimizing the fields. I only want to
> > create objects for the fields we use and I already made a column in the
> > spreadsheet "used by CanZE" for that. Now, there are two approaches to
> > this
> > 
> > 1) The options bit mapped field determines for which cars the field is
> > initialized. We now default it to 0x1f, meaning all cars, unless we need
> > differentiation. If we default the to 0x00 if the "used in CanZE", the
> > code
> > that processes the long string will simply skip over the unused fields.
> > 
> > 2) We can simply put two // in from of each line that is not used by
> > CanZE.
> > This way, if we by incident forget to set a "used by CanZE", we can
> > simply
> > remove the // and everything is fixed (instead of fiddling with the hex
> > code). It requires no code change, just spreadsheet change.
> > 
> > Personally I have a rather strong preference for option 2. It will make
> > everything (initialization and memory use) smaller and faster, more than
> > option 1, and it is easier to maintain.
> > 
> > What do you think?
> > 
> > Jeroen
> > 
> > On Mon, Jan 25, 2016 at 9:39 AM, Jeroen Meijer meijer.jwm@gmail.com
> > wrote:
> > 
> > > On the second, I agree.
> > > 
> > > On the first. I am not sure I agree, let me show you my highway trip to
> > > Amsterdam this AM, including a small holdup. The (very simple) Low Pass
> > > filter works fine I think
> > 
> > https://drive.google.com/file/d/1kbk6YemzH9tzOIKysTOq_O36RUw4zAk9WQ/view?usp=sharing
> > 
> > > New bug: Torque value doesn't display. I will fix that.
> > > 
> > > On Mon, Jan 25, 2016 at 8:56 AM, Bob Fisch notifications@github.com
> > > wrote:
> > > 
> > > > the new graph scale is better for values in the given range, but
> > > > actually
> > > > it now misses it's first need: display the instant average
> > > > consumption over
> > > > time. In fact, most of my values are outside the range, so I just
> > > > see some
> > > > lines going up and down.
> > > > 
> > > > The value in the upper bar does a good job. I think we need to enlarge
> > > > it, because for me it's somewhat too small right now.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/fesch/CanZE/pull/306#issuecomment-174430864.
> > > 
> > > ## 
> > > 
> > > Please use Signal to reach me on secure IM and VoIP
> > > http://sgnl.link/1KpeYmF
> > 
> > ## 
> > 
> > Please use Signal to reach me on secure IM and VoIP
> > http://sgnl.link/1KpeYmF
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/fesch/CanZE/pull/306#issuecomment-175284527.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fesch/CanZE/pull/306#issuecomment-175464051.

## 

Please use Signal to reach me on secure IM and VoIP http://sgnl.link/1KpeYmF

**Pull request merged**
