### PR TITLE
dataexportMode changes

### PR DESCRIPTION
**Pull request by chrismade**
so far only "settings" Dialog, check external SDcard exists/writeable, message if not, read/write preference file, manifest changed to WRITE external storage
yet no code for make data dir, open file, write data, close file on exit

### CODE REVIEW

**Comment by yoh-there** [comment]
Chris, unfortunately there is a merge conflict. I assume you have let your edit get a bit out of sync. Can happen in a weekend, as there is usually a lot of activity. I propose you pull from the the upstream to get in sync and resolve merging issues locally.  If you can't pull, this might help, see https://github.com/fesch/CanZE/wiki/5.-Issues-while-developing

**Comment by chrismade** [comment]
OK, will try tomorrow

**Comment by chrismade** [comment]
resolved 2 conflicts and merged the others without conflict - pulled activity_settings.xml fresh from master and re-applied my changes to this file

**Comment by yoh-there** [comment]
Merged and the activity_settings.xml is screwed not. Let me fix that.
Please don't touch for a few

**Pull request merged**
