### PR TITLE
Tyres to main, Firmware to technical

### PR DESCRIPTION
**Pull request by yoh-there**
Merge branch 'master' of https://github.com/fesch/CanZE

Conflicts:
    app/src/main/res/layout/fragment_experimental.xml

### CODE REVIEW

**Comment by fesch** [comment]
Why did you remove the firmware button from the main screen?

**Comment by fesch** [comment]
What about the license of your icon? (Nicer than mine from yesterday ....)

**Comment by yoh-there** [comment]
You made one yesterday? I am sorry, that must have crossed. I never noticed
:-(

**Comment by yoh-there** [comment]
I nicked the icon. Not good. Good thinking. Sorry I overwrote yours. Will you put it back in please?

I moved Firmware away as it is so "technical". If you disagree feel absolutely free to move it back, nothing released ;-)

**Pull request merged**
